import { TreeParameters } from '../types';

export const DEFAULT_PARAMETERS: TreeParameters = {
  // Seed & Hierarchy
  seed: 42,
  maxDepth: 6,
  branchCount: 3,
  branchProbability: 0.95,
  startBranchDepth: 1,
  symmetry: 0.25,

  // Trunk & Dimensions
  trunkLength: 8.0,
  lengthDecay: 0.72,
  lengthVariance: 0.18,
  trunkRadius: 0.55,
  radiusDecay: 0.65,
  taper: 0.25,
  minRadius: 0.015,
  radialSegments: 6,

  // Angles & Spatial Distribution
  branchAngle: 32,
  branchAngleVariance: 8,
  azimuthSpread: 137.5, // Golden angle
  azimuthVariance: 20,
  pitchVariance: 6,

  // Curvature & Gravitropism
  gravitropism: 0.18,
  segmentsPerBranch: 4,
  gnarliness: 0.22,
  twist: 12,

  // Foliage
  leavesEnabled: true,
  leafStartDepth: 4,
  leavesPerTip: 6,
  leafClusterRadius: 0.7,
  leafSize: 0.38,
  leafSizeVariance: 0.35,
  leafShape: 'oval',
  leafColor: '#2e6b36',
  leafColorTip: '#6ba847',
  leafColorVariation: 0.25,
  leafGravity: -0.2,
  leafDensity: 0.95,

  // Bark & Shading
  barkColor: '#432f21',
  barkColorTip: '#73573f',
  barkRoughness: 0.88,
  barkMetalness: 0.02,
  wireframe: false,
  flatShading: false,

  // Wind
  windEnabled: true,
  windStrength: 0.25,
  windSpeed: 1.2,
  windTurbulence: 0.45,
  windDirection: 45,

  // Growth
  growthProgress: 1.0,
  growthAnimation: false,
  growthSpeed: 0.25,

  // Environment
  backgroundColor: '#0f1115',
  groundEnabled: true,
  groundColor: '#1a1d24',
  groundRadius: 14.0,
  gridEnabled: true,
  sunIntensity: 2.2,
  sunElevation: 48,
  sunAzimuth: 65,
  ambientIntensity: 0.65,
  shadows: true,
  fogEnabled: true,
  fogDensity: 0.007,
  autoRotate: false,
  autoRotateSpeed: 1.0,
};

export const PRESETS: Record<string, Partial<TreeParameters>> = {
  'Ancient Oak': {
    seed: 104,
    maxDepth: 6,
    branchCount: 3,
    branchProbability: 0.95,
    startBranchDepth: 1,
    symmetry: 0.15,
    trunkLength: 7.5,
    lengthDecay: 0.75,
    lengthVariance: 0.2,
    trunkRadius: 0.95,
    radiusDecay: 0.68,
    taper: 0.35,
    branchAngle: 38,
    branchAngleVariance: 12,
    azimuthSpread: 120,
    gravitropism: 0.15,
    segmentsPerBranch: 4,
    gnarliness: 0.38,
    twist: 18,
    leavesEnabled: true,
    leafStartDepth: 4,
    leavesPerTip: 8,
    leafClusterRadius: 0.9,
    leafSize: 0.45,
    leafShape: 'oval',
    leafColor: '#2b5c2a',
    leafColorTip: '#528a38',
    barkColor: '#362419',
    barkColorTip: '#5c4331',
  },

  'Weeping Willow': {
    seed: 520,
    maxDepth: 7,
    branchCount: 3,
    branchProbability: 0.98,
    startBranchDepth: 2,
    symmetry: 0.2,
    trunkLength: 9.0,
    lengthDecay: 0.82,
    lengthVariance: 0.25,
    trunkRadius: 0.5,
    radiusDecay: 0.62,
    branchAngle: 42,
    branchAngleVariance: 14,
    azimuthSpread: 137.5,
    gravitropism: -0.62, // Strong cascading downward droop!
    segmentsPerBranch: 5,
    gnarliness: 0.18,
    twist: -10,
    leavesEnabled: true,
    leafStartDepth: 5,
    leavesPerTip: 10,
    leafClusterRadius: 1.2,
    leafSize: 0.32,
    leafShape: 'needle',
    leafColor: '#4f7d3a',
    leafColorTip: '#8ebf5c',
    leafGravity: -0.8,
    barkColor: '#3d3429',
  },

  'Japanese Bonsai': {
    seed: 88,
    maxDepth: 5,
    branchCount: 2,
    branchProbability: 0.92,
    startBranchDepth: 1,
    symmetry: 0.05,
    trunkLength: 6.0,
    lengthDecay: 0.72,
    lengthVariance: 0.3,
    trunkRadius: 0.7,
    radiusDecay: 0.65,
    branchAngle: 45,
    branchAngleVariance: 22,
    azimuthSpread: 155,
    gravitropism: 0.28,
    segmentsPerBranch: 5,
    gnarliness: 0.65, // Highly gnarled, sculptural trunk
    twist: 45,
    leavesEnabled: true,
    leafStartDepth: 3,
    leavesPerTip: 12,
    leafClusterRadius: 0.6,
    leafSize: 0.3,
    leafShape: 'disc',
    leafColor: '#1d4d2a',
    leafColorTip: '#367a42',
    barkColor: '#2b2118',
    barkRoughness: 0.95,
  },

  'Sakura (Cherry Blossom)': {
    seed: 246,
    maxDepth: 6,
    branchCount: 3,
    branchProbability: 0.96,
    startBranchDepth: 2,
    symmetry: 0.22,
    trunkLength: 8.0,
    lengthDecay: 0.76,
    lengthVariance: 0.15,
    trunkRadius: 0.48,
    radiusDecay: 0.64,
    branchAngle: 36,
    branchAngleVariance: 10,
    azimuthSpread: 137.5,
    gravitropism: 0.12,
    segmentsPerBranch: 4,
    gnarliness: 0.28,
    leavesEnabled: true,
    leafStartDepth: 4,
    leavesPerTip: 8,
    leafClusterRadius: 0.8,
    leafSize: 0.4,
    leafShape: 'blossom',
    leafColor: '#f28ebb', // Vivid sakura petal pink
    leafColorTip: '#ffd1e3',
    leafColorVariation: 0.35,
    barkColor: '#2d1f1f',
    barkColorTip: '#523a3a',
  },

  'Nordic Pine (Conifer)': {
    seed: 777,
    maxDepth: 6,
    branchCount: 4,
    branchProbability: 0.95,
    startBranchDepth: 2,
    symmetry: 0.7,
    trunkLength: 12.0,
    lengthDecay: 0.62,
    lengthVariance: 0.08,
    trunkRadius: 0.58,
    radiusDecay: 0.62,
    branchAngle: 58, // Horizontal whorled tiers
    branchAngleVariance: 5,
    azimuthSpread: 90,
    gravitropism: 0.05,
    segmentsPerBranch: 2,
    gnarliness: 0.06,
    twist: 0,
    leavesEnabled: true,
    leafStartDepth: 3,
    leavesPerTip: 14,
    leafClusterRadius: 0.6,
    leafSize: 0.25,
    leafShape: 'needle',
    leafColor: '#17361f',
    leafColorTip: '#2b5735',
    barkColor: '#42281a',
  },

  'Baobab (Bottle Tree)': {
    seed: 412,
    maxDepth: 5,
    branchCount: 3,
    branchProbability: 0.9,
    startBranchDepth: 1,
    symmetry: 0.3,
    trunkLength: 9.0,
    lengthDecay: 0.58,
    lengthVariance: 0.12,
    trunkRadius: 1.8, // Enormous massive trunk!
    radiusDecay: 0.52,
    taper: 0.6,
    branchAngle: 48,
    branchAngleVariance: 12,
    azimuthSpread: 120,
    gravitropism: 0.25,
    segmentsPerBranch: 4,
    gnarliness: 0.18,
    leavesEnabled: true,
    leafStartDepth: 4,
    leavesPerTip: 5,
    leafClusterRadius: 0.6,
    leafSize: 0.35,
    leafShape: 'oval',
    leafColor: '#4a692e',
    leafColorTip: '#749e49',
    barkColor: '#57463a',
    barkRoughness: 0.9,
  },

  'Golden Acacia (Savannah)': {
    seed: 933,
    maxDepth: 6,
    branchCount: 3,
    branchProbability: 0.94,
    startBranchDepth: 3, // Tall bare trunk before spreading canopy
    symmetry: 0.3,
    trunkLength: 10.0,
    lengthDecay: 0.76,
    lengthVariance: 0.15,
    trunkRadius: 0.5,
    radiusDecay: 0.65,
    branchAngle: 50,
    branchAngleVariance: 10,
    azimuthSpread: 137.5,
    gravitropism: 0.35, // Flat umbrella canopy
    segmentsPerBranch: 4,
    gnarliness: 0.22,
    leavesEnabled: true,
    leafStartDepth: 4,
    leavesPerTip: 7,
    leafClusterRadius: 0.7,
    leafSize: 0.32,
    leafShape: 'oval',
    leafColor: '#c9962a', // Amber savannah foliage
    leafColorTip: '#dfbc4e',
    barkColor: '#3d3023',
  },

  'Dead Winter Birch': {
    seed: 333,
    maxDepth: 6,
    branchCount: 2,
    branchProbability: 0.95,
    startBranchDepth: 1,
    symmetry: 0.1,
    trunkLength: 8.5,
    lengthDecay: 0.74,
    lengthVariance: 0.25,
    trunkRadius: 0.42,
    radiusDecay: 0.65,
    branchAngle: 34,
    branchAngleVariance: 16,
    azimuthSpread: 140,
    gravitropism: 0.22,
    segmentsPerBranch: 5,
    gnarliness: 0.45,
    twist: 25,
    leavesEnabled: false, // Stark bare branches
    barkColor: '#d6d1cb', // Pale silver/birch white
    barkColorTip: '#7d746d',
    barkRoughness: 0.8,
  },

  'Pythagorean Fractal': {
    seed: 1,
    maxDepth: 7,
    branchCount: 2,
    branchProbability: 1.0,
    startBranchDepth: 1,
    symmetry: 1.0, // Absolute mathematical symmetry
    trunkLength: 7.0,
    lengthDecay: 0.707, // 1 / sqrt(2)
    lengthVariance: 0.0,
    trunkRadius: 0.4,
    radiusDecay: 0.707,
    taper: 0.0,
    branchAngle: 45,
    branchAngleVariance: 0,
    azimuthSpread: 180,
    azimuthVariance: 0,
    pitchVariance: 0,
    gravitropism: 0.0,
    segmentsPerBranch: 1,
    gnarliness: 0.0,
    twist: 0,
    leavesEnabled: false,
    barkColor: '#3080e8',
    barkColorTip: '#00ffff',
  },

  'Cyber Neon Tree': {
    seed: 404,
    maxDepth: 6,
    branchCount: 3,
    branchProbability: 1.0,
    startBranchDepth: 1,
    symmetry: 0.8,
    trunkLength: 8.0,
    lengthDecay: 0.72,
    lengthVariance: 0.0,
    trunkRadius: 0.35,
    radiusDecay: 0.68,
    branchAngle: 40,
    branchAngleVariance: 0,
    azimuthSpread: 120,
    azimuthVariance: 0,
    gravitropism: 0.0,
    segmentsPerBranch: 2,
    gnarliness: 0.0,
    twist: 30,
    wireframe: true,
    leavesEnabled: true,
    leafStartDepth: 4,
    leavesPerTip: 4,
    leafClusterRadius: 0.5,
    leafSize: 0.35,
    leafShape: 'quad',
    leafColor: '#ff0077', // Cyberpunk neon pink & cyan
    leafColorTip: '#00f6ff',
    barkColor: '#00f6ff',
    barkColorTip: '#ff0077',
    backgroundColor: '#050608',
  },
};
